name = "LogFixPoints"
uuid = "92e8f241-9161-42bc-865b-6902e0af5511"
authors = ["milankl"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
